language: go

go:
- 1.2

before_install: 
- sudo apt-get update
- sudo apt-get install dnsutils

install:
- go get code.google.com/p/go.tools/cmd/vet
- go get github.com/golang/lint/golint

script: bin/ci
